import os

# Setup local build environment and paths
Import('env')
local_env = env.Clone()
root = os.path.dirname(Dir('.').srcnode().abspath)
media_path = os.path.join(root, 'media')
common_path = os.path.join(root, 'common')

# Build Requirements tex file
local_env.Mako('document.tex', 'document.tex.mako')

# Build Document
local_env.PrependENVPath('PATH', common_path)
local_env.Append(TEXINPUTS=[common_path, media_path])
pdf = local_env.PDF('document.tex')
install = local_env.InstallAs(
    'SConsMakoTex.pdf', pdf)
Return('install')
